//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjBookStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAuthor
    {
        public int fAuthorID { get; set; }
        public string fAuthorName { get; set; }
        public string fAuthorPhone { get; set; }
        public string fAuthorEmail { get; set; }
        public string fAuthorAddress { get; set; }
        public string fAuthorGender { get; set; }
        public string fAuthorNationality { get; set; }
        public string fAuthorImagePath { get; set; }
    }
}
