//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjBookStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCard
    {
        public int fEmployeeId { get; set; }
        public Nullable<System.DateTime> fStart { get; set; }
        public Nullable<System.DateTime> fOff { get; set; }
        public Nullable<int> fWorktime { get; set; }
    
        public virtual tEmployee tEmployee { get; set; }
    }
}
