//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjBookStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class tEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tEmployee()
        {
            this.tCustomerService = new HashSet<tCustomerService>();
            this.tExpenseReports = new HashSet<tExpenseReports>();
            this.tExpenseReports1 = new HashSet<tExpenseReports>();
        }
    
        public int fEmployeeId { get; set; }
        public string fEmployeeName { get; set; }
        public string fPhone { get; set; }
        public string fEmail { get; set; }
        public string fAddress { get; set; }
        public string fPassword { get; set; }
        public Nullable<int> fDepartmentId { get; set; }
        public Nullable<int> fPositionId { get; set; }
        public Nullable<decimal> fWage { get; set; }
        public string fImagePath { get; set; }
        public Nullable<bool> fEnable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCustomerService> tCustomerService { get; set; }
        public virtual tDepartments tDepartments { get; set; }
        public virtual tCard tCard { get; set; }
        public virtual tPosition tPosition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tExpenseReports> tExpenseReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tExpenseReports> tExpenseReports1 { get; set; }
    }
}
