//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjBookStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class tExpenseReports
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tExpenseReports()
        {
            this.tExpenseItems = new HashSet<tExpenseItems>();
        }
    
        public int fReportId { get; set; }
        public Nullable<int> fEmployeeId { get; set; }
        public Nullable<System.DateTime> fDate { get; set; }
        public Nullable<bool> fStatus { get; set; }
        public int fApproverId { get; set; }
        public Nullable<System.DateTime> fApprovalDate { get; set; }
        public Nullable<decimal> fTotal { get; set; }
    
        public virtual tEmployee tEmployee { get; set; }
        public virtual tEmployee tEmployee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tExpenseItems> tExpenseItems { get; set; }
    }
}
