//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjBookStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class tFundrasingPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tFundrasingPlan()
        {
            this.tMember = new HashSet<tMember>();
        }
    
        public int fPlanID { get; set; }
        public string fPlanName { get; set; }
        public decimal fPlanAmount { get; set; }
        public string fPlanDescription { get; set; }
        public int fFundrasingID { get; set; }
    
        public virtual tFundrasing tFundrasing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tMember> tMember { get; set; }
    }
}
